/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package database_kasa;
import java.awt.Font;
import javax.swing.JScrollPane;
import javax.swing.ScrollPaneConstants;
import javax.swing.UIManager;

/**
 *
 * @author Kevin
 */
public class mainPanel extends javax.swing.JFrame {

    /**
     * Creates new form mainPanel
     */
    @SuppressWarnings("empty-statement")
    public mainPanel() {
        UIManager.getLookAndFeelDefaults().put("defaultFont", new Font("Arial", Font.PLAIN, 16));
        String tenantSQL = "select name from tenant";
        String propertySQL = "select address from property";
        String ownerSQL = "select name from owner";
        String repairSQL = "select date, address from repairs";
        String repairCompanySQL = "select name from repairCompany";
        String storeSQL = "select name, address from store";
        
        tenantCB= new String[]{"Alice"};
        propertyCB = new String[]{"222 road"};
        ownerCB = new String[]{"Bob"};
        repairCB = new String[]{"05/12/13 2Road"};
        repairCompanyCB  = new String[]{"Repair Co"};
        storeCB = new String[]{"Home Depot, 123 street"};
        countyCB = new String[]{"Montgomery", "Prince Georges"};
        initComponents(); 
         
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel7 = new javax.swing.JLabel();
        jPanelMain = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jPaneInput = new javax.swing.JTabbedPane();
        jPanelInOwner = new javax.swing.JPanel();
        jTextInOwnerName = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jTextInOwnerEmail = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextInOwnerPhoneNum = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jButtonOwnerAdd = new javax.swing.JButton();
        jButtonOwnerClear = new javax.swing.JButton();
        jPanelInOwnerGroup = new javax.swing.JPanel();
        jButtonClear = new javax.swing.JButton();
        jButtonOGAdd = new javax.swing.JButton();
        jCBInOGOwner = new javax.swing.JComboBox<>();
        jCBInOGGroup = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanelInPayment = new javax.swing.JPanel();
        jButtonPayAdd = new javax.swing.JButton();
        jButtonPayClear = new javax.swing.JButton();
        jCBInPayTenant = new javax.swing.JComboBox<>();
        jCBInPayProperty = new javax.swing.JComboBox<>();
        jLabel21 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jTextInPayTenant = new javax.swing.JTextField();
        jTextInPayOwner = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jCBInPayTM = new javax.swing.JComboBox<>();
        jCBInPayTY = new javax.swing.JComboBox<>();
        jCBInPayOM = new javax.swing.JComboBox<>();
        jCBInPayOY = new javax.swing.JComboBox<>();
        jPanelInRepair = new javax.swing.JPanel();
        jButtonRepairAdd = new javax.swing.JButton();
        jButtonRepairClear = new javax.swing.JButton();
        jCBInRepairProperty = new javax.swing.JComboBox<>();
        jLabel32 = new javax.swing.JLabel();
        jTextInRepairDateM = new javax.swing.JTextField();
        jLabel33 = new javax.swing.JLabel();
        jTextInRepairDateD = new javax.swing.JTextField();
        jTextInRepairDateY = new javax.swing.JTextField();
        jCBInRepairRC = new javax.swing.JComboBox<>();
        jCBInRepairStore = new javax.swing.JComboBox<>();
        jLabelRC = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jTextInRepairMCost = new javax.swing.JTextField();
        jTextInRepairRCost = new javax.swing.JTextField();
        jTextInRepairman = new javax.swing.JTextField();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jPanelInStores = new javax.swing.JPanel();
        jButtonStoreAdd = new javax.swing.JButton();
        jButtonStoreClear = new javax.swing.JButton();
        jTextInStoreName = new javax.swing.JTextField();
        jTextInStoreAddress = new javax.swing.JTextField();
        jTextInStorePhone = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jPanelInRepairCompany = new javax.swing.JPanel();
        jButtonRCAdd = new javax.swing.JButton();
        jButtonRCClear = new javax.swing.JButton();
        jTextInRCName = new javax.swing.JTextField();
        jTextInRCPhone = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jPanelInProperty = new javax.swing.JPanel();
        jButtonPropAdd = new javax.swing.JButton();
        jButtonProbClear = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jPanelInProp = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jCBInPropertyOwner = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        jTextInPropertySize = new javax.swing.JTextField();
        jCBInPropertyYear = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jTextInPropertyAddress = new javax.swing.JTextField();
        jTextInPropertyZip = new javax.swing.JTextField();
        jTextInPropertyCity = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jCBInPropertyCounty = new javax.swing.JComboBox<>();
        jLabel14 = new javax.swing.JLabel();
        jCBInPropertyBed = new javax.swing.JComboBox<>();
        jCBInPropertyBath = new javax.swing.JComboBox<>();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jCBInPropertyType = new javax.swing.JComboBox<>();
        jLabel17 = new javax.swing.JLabel();
        jTextInPropertyVar1 = new javax.swing.JTextField();
        jTextInPropertyVar2 = new javax.swing.JTextField();
        jTextInPropertyVar3 = new javax.swing.JTextField();
        propertyVar1 = new javax.swing.JLabel();
        propertyVar2 = new javax.swing.JLabel();
        propertyVar3 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jCBInPropertyRS = new javax.swing.JComboBox<>();
        propertyVar4 = new javax.swing.JLabel();
        jTextInPropertyVar4 = new javax.swing.JTextField();
        propertyVar5 = new javax.swing.JLabel();
        jTextInPropertyVar5 = new javax.swing.JTextField();
        propertyVar6 = new javax.swing.JLabel();
        jTextInPropertyVar6 = new javax.swing.JTextField();
        jPanelInTenant = new javax.swing.JPanel();
        jButtonTenantAdd = new javax.swing.JButton();
        jButtonTenantClear = new javax.swing.JButton();
        jTextInTenantName = new javax.swing.JTextField();
        jTextInTenantEmail = new javax.swing.JTextField();
        jTextInTenantPhone = new javax.swing.JTextField();
        jCBInTenantProperty = new javax.swing.JComboBox<>();
        jCBInTenantDependents = new javax.swing.JComboBox<>();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabeTlPN = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanelOutTenant = new javax.swing.JPanel();
        jCBOutTenantName = new javax.swing.JComboBox<>();
        jLabel39 = new javax.swing.JLabel();
        jButtonOutTenantLoad = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTAOutTenantInfo = new javax.swing.JTextArea();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTAOutTenantPay = new javax.swing.JTextArea();
        jPanelOutProp = new javax.swing.JPanel();
        jCBOutProp = new javax.swing.JComboBox<>();
        jButtonOutPropLoad = new javax.swing.JButton();
        jLabel34 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTAOutPropInfo = new javax.swing.JTextArea();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTAOutPropRepair = new javax.swing.JTextArea();
        jPanelOutRepair = new javax.swing.JPanel();
        jLabel40 = new javax.swing.JLabel();
        jCBOutRepair = new javax.swing.JComboBox<>();
        jButtonOutRepair = new javax.swing.JButton();
        jScrollPane7 = new javax.swing.JScrollPane();
        jTextArea5 = new javax.swing.JTextArea();

        jLabel7.setText("jLabel7");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.BorderLayout());

        jLabel1.setText("Name");

        jLabel2.setText("Email");

        jLabel3.setText("Phone Number");

        jButtonOwnerAdd.setText("Add");
        jButtonOwnerAdd.setMaximumSize(new java.awt.Dimension(70, 29));
        jButtonOwnerAdd.setMinimumSize(new java.awt.Dimension(70, 29));
        jButtonOwnerAdd.setPreferredSize(null);
        jButtonOwnerAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOwnerAddActionPerformed(evt);
            }
        });

        jButtonOwnerClear.setText("Clear");
        jButtonOwnerClear.setMaximumSize(new java.awt.Dimension(70, 29));
        jButtonOwnerClear.setMinimumSize(new java.awt.Dimension(70, 29));
        jButtonOwnerClear.setPreferredSize(null);
        jButtonOwnerClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOwnerClearActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelInOwnerLayout = new javax.swing.GroupLayout(jPanelInOwner);
        jPanelInOwner.setLayout(jPanelInOwnerLayout);
        jPanelInOwnerLayout.setHorizontalGroup(
            jPanelInOwnerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelInOwnerLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanelInOwnerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jTextInOwnerName, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jTextInOwnerEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jTextInOwnerPhoneNum, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(441, 441, 441))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelInOwnerLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonOwnerAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56)
                .addComponent(jButtonOwnerClear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(238, 238, 238))
        );
        jPanelInOwnerLayout.setVerticalGroup(
            jPanelInOwnerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelInOwnerLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel1)
                .addGap(0, 0, 0)
                .addComponent(jTextInOwnerName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addComponent(jLabel2)
                .addGap(1, 1, 1)
                .addComponent(jTextInOwnerEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(jLabel3)
                .addGap(0, 0, 0)
                .addComponent(jTextInOwnerPhoneNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 290, Short.MAX_VALUE)
                .addGroup(jPanelInOwnerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonOwnerClear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonOwnerAdd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPaneInput.addTab("Owner", jPanelInOwner);

        jButtonClear.setText("Clear");
        jButtonClear.setMaximumSize(new java.awt.Dimension(70, 29));
        jButtonClear.setMinimumSize(new java.awt.Dimension(70, 29));
        jButtonClear.setPreferredSize(null);

        jButtonOGAdd.setText("Add");
        jButtonOGAdd.setMaximumSize(new java.awt.Dimension(70, 29));
        jButtonOGAdd.setMinimumSize(new java.awt.Dimension(70, 29));
        jButtonOGAdd.setPreferredSize(null);
        jButtonOGAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOGAddActionPerformed(evt);
            }
        });

        jCBInOGOwner.setModel(new javax.swing.DefaultComboBoxModel(ownerCB));

        jCBInOGGroup.setModel(new javax.swing.DefaultComboBoxModel(ownerCB));

        jLabel4.setText("Add owner");

        jLabel5.setText("To Group:");

        javax.swing.GroupLayout jPanelInOwnerGroupLayout = new javax.swing.GroupLayout(jPanelInOwnerGroup);
        jPanelInOwnerGroup.setLayout(jPanelInOwnerGroupLayout);
        jPanelInOwnerGroupLayout.setHorizontalGroup(
            jPanelInOwnerGroupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelInOwnerGroupLayout.createSequentialGroup()
                .addContainerGap(244, Short.MAX_VALUE)
                .addComponent(jButtonOGAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56)
                .addComponent(jButtonClear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(238, 238, 238))
            .addGroup(jPanelInOwnerGroupLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelInOwnerGroupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCBInOGGroup, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCBInOGOwner, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelInOwnerGroupLayout.setVerticalGroup(
            jPanelInOwnerGroupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelInOwnerGroupLayout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(jLabel4)
                .addGap(0, 0, 0)
                .addComponent(jCBInOGOwner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(0, 0, 0)
                .addComponent(jCBInOGGroup, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(300, 300, 300)
                .addGroup(jPanelInOwnerGroupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonClear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonOGAdd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPaneInput.addTab("Owner Group", jPanelInOwnerGroup);

        jButtonPayAdd.setText("Add");
        jButtonPayAdd.setMaximumSize(new java.awt.Dimension(70, 29));
        jButtonPayAdd.setMinimumSize(new java.awt.Dimension(70, 29));
        jButtonPayAdd.setPreferredSize(null);
        jButtonPayAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPayAddActionPerformed(evt);
            }
        });

        jButtonPayClear.setText("Clear");
        jButtonPayClear.setMaximumSize(new java.awt.Dimension(70, 29));
        jButtonPayClear.setMinimumSize(new java.awt.Dimension(70, 29));
        jButtonPayClear.setPreferredSize(null);
        jButtonPayClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPayClearActionPerformed(evt);
            }
        });

        jCBInPayTenant.setModel(new javax.swing.DefaultComboBoxModel(tenantCB));

        jCBInPayProperty.setModel(new javax.swing.DefaultComboBoxModel(propertyCB));

        jLabel21.setText("Tenant");

        jLabel24.setText("Property");

        jLabel25.setText("Tenant Payment Amount");

        jLabel26.setText("Owner Payment Amount");

        jCBInPayTM.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December" }));

        jCBInPayTY.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2010", "2011", "2012", "2013", "2014", "2015", "2016", "2017" }));

        jCBInPayOM.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December" }));

        jCBInPayOY.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2010", "2011", "2012", "2013", "2014", "2015", "2016", "2017" }));

        javax.swing.GroupLayout jPanelInPaymentLayout = new javax.swing.GroupLayout(jPanelInPayment);
        jPanelInPayment.setLayout(jPanelInPaymentLayout);
        jPanelInPaymentLayout.setHorizontalGroup(
            jPanelInPaymentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelInPaymentLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelInPaymentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelInPaymentLayout.createSequentialGroup()
                        .addGroup(jPanelInPaymentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jCBInPayTenant, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jCBInPayProperty, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanelInPaymentLayout.createSequentialGroup()
                                .addGap(0, 229, Short.MAX_VALUE)
                                .addComponent(jButtonPayAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(56, 56, 56)
                        .addComponent(jButtonPayClear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(238, 238, 238))
                    .addGroup(jPanelInPaymentLayout.createSequentialGroup()
                        .addComponent(jLabel21)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanelInPaymentLayout.createSequentialGroup()
                        .addGroup(jPanelInPaymentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel24)
                            .addComponent(jLabel25, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextInPayOwner)
                            .addComponent(jLabel26, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextInPayTenant))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanelInPaymentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jCBInPayTM, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jCBInPayOM, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanelInPaymentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jCBInPayTY, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jCBInPayOY, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(133, 133, 133))))
        );
        jPanelInPaymentLayout.setVerticalGroup(
            jPanelInPaymentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelInPaymentLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel21)
                .addGap(1, 1, 1)
                .addComponent(jCBInPayTenant, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(jLabel24)
                .addGap(0, 0, 0)
                .addComponent(jCBInPayProperty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jLabel25)
                .addGap(0, 0, 0)
                .addGroup(jPanelInPaymentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextInPayTenant, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCBInPayTM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCBInPayTY, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addComponent(jLabel26)
                .addGap(1, 1, 1)
                .addGroup(jPanelInPaymentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextInPayOwner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCBInPayOM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCBInPayOY, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 248, Short.MAX_VALUE)
                .addGroup(jPanelInPaymentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonPayClear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonPayAdd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPaneInput.addTab("Payment", jPanelInPayment);

        jButtonRepairAdd.setText("Add");
        jButtonRepairAdd.setMaximumSize(new java.awt.Dimension(70, 29));
        jButtonRepairAdd.setMinimumSize(new java.awt.Dimension(70, 29));
        jButtonRepairAdd.setPreferredSize(null);
        jButtonRepairAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRepairAddActionPerformed(evt);
            }
        });

        jButtonRepairClear.setText("Clear");
        jButtonRepairClear.setMaximumSize(new java.awt.Dimension(70, 29));
        jButtonRepairClear.setMinimumSize(new java.awt.Dimension(70, 29));
        jButtonRepairClear.setPreferredSize(null);
        jButtonRepairClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRepairClearActionPerformed(evt);
            }
        });

        jCBInRepairProperty.setModel(new javax.swing.DefaultComboBoxModel(propertyCB));

        jLabel32.setText("Property");

        jLabel33.setText("Repair Date(MM DD YYYY)");

        jCBInRepairRC.setModel(new javax.swing.DefaultComboBoxModel(repairCompanyCB));

        jCBInRepairStore.setModel(new javax.swing.DefaultComboBoxModel(storeCB));

        jLabelRC.setText("Repair Company");

        jLabel35.setText("Material Source");

        jLabel36.setText("Material Cost");

        jLabel37.setText("Repairman Name");

        jLabel38.setText("Repair Cost");

        javax.swing.GroupLayout jPanelInRepairLayout = new javax.swing.GroupLayout(jPanelInRepair);
        jPanelInRepair.setLayout(jPanelInRepairLayout);
        jPanelInRepairLayout.setHorizontalGroup(
            jPanelInRepairLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelInRepairLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelInRepairLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelInRepairLayout.createSequentialGroup()
                        .addGroup(jPanelInRepairLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jCBInRepairProperty, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanelInRepairLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jButtonRepairAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(56, 56, 56)
                        .addComponent(jButtonRepairClear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(238, 238, 238))
                    .addGroup(jPanelInRepairLayout.createSequentialGroup()
                        .addComponent(jLabel32)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanelInRepairLayout.createSequentialGroup()
                        .addGroup(jPanelInRepairLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel33)
                            .addGroup(jPanelInRepairLayout.createSequentialGroup()
                                .addComponent(jTextInRepairDateM, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextInRepairDateD, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextInRepairDateY, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanelInRepairLayout.createSequentialGroup()
                                .addGroup(jPanelInRepairLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jCBInRepairRC, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabelRC)
                                    .addComponent(jLabel37)
                                    .addComponent(jTextInRepairman, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(155, 155, 155)
                                .addGroup(jPanelInRepairLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel35)
                                    .addComponent(jCBInRepairStore, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanelInRepairLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jTextInRepairMCost, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel36, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                            .addComponent(jLabel38)
                            .addComponent(jTextInRepairRCost, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanelInRepairLayout.setVerticalGroup(
            jPanelInRepairLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelInRepairLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel32)
                .addGap(2, 2, 2)
                .addComponent(jCBInRepairProperty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(jLabel33)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelInRepairLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextInRepairDateM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextInRepairDateD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextInRepairDateY, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(54, 54, 54)
                .addGroup(jPanelInRepairLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelRC)
                    .addComponent(jLabel35))
                .addGap(0, 0, 0)
                .addGroup(jPanelInRepairLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCBInRepairRC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCBInRepairStore, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanelInRepairLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel36, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel37))
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanelInRepairLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextInRepairMCost)
                    .addComponent(jTextInRepairman))
                .addGap(26, 26, 26)
                .addComponent(jLabel38)
                .addGap(1, 1, 1)
                .addComponent(jTextInRepairRCost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 178, Short.MAX_VALUE)
                .addGroup(jPanelInRepairLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonRepairClear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonRepairAdd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPaneInput.addTab("Repair", jPanelInRepair);

        jButtonStoreAdd.setText("Add");
        jButtonStoreAdd.setMaximumSize(new java.awt.Dimension(70, 29));
        jButtonStoreAdd.setMinimumSize(new java.awt.Dimension(70, 29));
        jButtonStoreAdd.setPreferredSize(null);
        jButtonStoreAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonStoreAddActionPerformed(evt);
            }
        });

        jButtonStoreClear.setText("Clear");
        jButtonStoreClear.setMaximumSize(new java.awt.Dimension(70, 29));
        jButtonStoreClear.setMinimumSize(new java.awt.Dimension(70, 29));
        jButtonStoreClear.setPreferredSize(null);
        jButtonStoreClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonStoreClearActionPerformed(evt);
            }
        });

        jLabel29.setText("Store Name");

        jLabel30.setText("Store Address");

        jLabel31.setText("Store Phone Number");

        javax.swing.GroupLayout jPanelInStoresLayout = new javax.swing.GroupLayout(jPanelInStores);
        jPanelInStores.setLayout(jPanelInStoresLayout);
        jPanelInStoresLayout.setHorizontalGroup(
            jPanelInStoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelInStoresLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelInStoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelInStoresLayout.createSequentialGroup()
                        .addGroup(jPanelInStoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTextInStoreAddress, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelInStoresLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 229, Short.MAX_VALUE)
                                .addComponent(jButtonStoreAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(56, 56, 56)
                        .addComponent(jButtonStoreClear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(238, 238, 238))
                    .addGroup(jPanelInStoresLayout.createSequentialGroup()
                        .addGroup(jPanelInStoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextInStoreName, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextInStorePhone, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanelInStoresLayout.createSequentialGroup()
                        .addGroup(jPanelInStoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel29)
                            .addComponent(jLabel30)
                            .addComponent(jLabel31))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanelInStoresLayout.setVerticalGroup(
            jPanelInStoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelInStoresLayout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(jLabel29)
                .addGap(1, 1, 1)
                .addComponent(jTextInStoreName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(jLabel30)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextInStoreAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(jLabel31)
                .addGap(1, 1, 1)
                .addComponent(jTextInStorePhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 273, Short.MAX_VALUE)
                .addGroup(jPanelInStoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonStoreClear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonStoreAdd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPaneInput.addTab("Store", jPanelInStores);

        jButtonRCAdd.setText("Add");
        jButtonRCAdd.setMaximumSize(new java.awt.Dimension(70, 29));
        jButtonRCAdd.setMinimumSize(new java.awt.Dimension(70, 29));
        jButtonRCAdd.setPreferredSize(null);
        jButtonRCAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRCAddActionPerformed(evt);
            }
        });

        jButtonRCClear.setText("Clear");
        jButtonRCClear.setMaximumSize(new java.awt.Dimension(70, 29));
        jButtonRCClear.setMinimumSize(new java.awt.Dimension(70, 29));
        jButtonRCClear.setPreferredSize(null);

        jLabel27.setText("Company Name");

        jLabel28.setText("Phone Number");

        javax.swing.GroupLayout jPanelInRepairCompanyLayout = new javax.swing.GroupLayout(jPanelInRepairCompany);
        jPanelInRepairCompany.setLayout(jPanelInRepairCompanyLayout);
        jPanelInRepairCompanyLayout.setHorizontalGroup(
            jPanelInRepairCompanyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelInRepairCompanyLayout.createSequentialGroup()
                .addContainerGap(244, Short.MAX_VALUE)
                .addComponent(jButtonRCAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56)
                .addComponent(jButtonRCClear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(238, 238, 238))
            .addGroup(jPanelInRepairCompanyLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelInRepairCompanyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextInRCName, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextInRCPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel27)
                    .addComponent(jLabel28))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelInRepairCompanyLayout.setVerticalGroup(
            jPanelInRepairCompanyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelInRepairCompanyLayout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(jLabel27)
                .addGap(1, 1, 1)
                .addComponent(jTextInRCName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55)
                .addComponent(jLabel28)
                .addGap(0, 0, 0)
                .addComponent(jTextInRCPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 327, Short.MAX_VALUE)
                .addGroup(jPanelInRepairCompanyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonRCClear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonRCAdd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPaneInput.addTab("Repair Company", jPanelInRepairCompany);

        jButtonPropAdd.setText("Add");
        jButtonPropAdd.setMaximumSize(new java.awt.Dimension(70, 29));
        jButtonPropAdd.setMinimumSize(new java.awt.Dimension(70, 29));
        jButtonPropAdd.setPreferredSize(null);
        jButtonPropAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPropAddActionPerformed(evt);
            }
        });

        jButtonProbClear.setText("Clear");
        jButtonProbClear.setMaximumSize(new java.awt.Dimension(70, 29));
        jButtonProbClear.setMinimumSize(new java.awt.Dimension(70, 29));
        jButtonProbClear.setPreferredSize(null);

        jLabel6.setText("Address");

        jPanelInProp.setBackground(new java.awt.Color(204, 204, 255));

        jLabel8.setText("Address");

        jCBInPropertyOwner.setModel(new javax.swing.DefaultComboBoxModel(ownerCB));

        jLabel9.setText("Owner");

        jCBInPropertyYear.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1917", "1918", "1919", "1920", "1921", "1922", "1923", "1924", "1925", "1926", "1927", "1928", "1929", "1930", "1931", "1932", "1933", "1934", "1935", "1936", "1937", "1938", "1939", "1940", "1941", "1942", "1943", "1944", "1945", "1946", "1947", "1948", "1949", "1950", "1951", "1952", "1953", "1954", "1955", "1956", "1957", "1958", "1959", "1960", "1961", "1962", "1963", "1964", "1965", "1966", "1967", "1968", "1969", "1970", "1971", "1972", "1973", "1974", "1975", "1976", "1977", "1978", "1979", "1980", "1981", "1982", "1983", "1984", "1985", "1986", "1987", "1988", "1989", "1990", "1991", "1992", "1993", "1994", "1995", "1996", "1997", "1998", "1999", "2000", "2001", "2002", "2003", "2004", "2005", "2006", "2007", "2008", "2009", "2010", "2011", "2012", "2013", "2014", "2015", "2016", "2017" }));

        jLabel10.setText("Size");

        jLabel11.setText("Year Built");

        jLabel12.setText("City");

        jLabel13.setText("Zip");

        jCBInPropertyCounty.setModel(new javax.swing.DefaultComboBoxModel(countyCB));

        jLabel14.setText("County");

        jCBInPropertyBed.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5", "6", "7+", " " }));

        jCBInPropertyBath.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5", "6", "7+" }));

        jLabel15.setText("Bathroom");

        jLabel16.setText("Bedroom");

        jCBInPropertyType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Condo", "Townhouse", "Single Family" }));
        jCBInPropertyType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCBInPropertyTypeActionPerformed(evt);
            }
        });

        jLabel17.setText("Property Type");

        propertyVar1.setText("Choose a Property Type");

        jLabel18.setText("Rental/Sale");

        jCBInPropertyRS.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Rental", "Sale" }));
        jCBInPropertyRS.setPreferredSize(new java.awt.Dimension(170, 26));
        jCBInPropertyRS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCBInPropertyRSActionPerformed(evt);
            }
        });

        propertyVar4.setText("Choose Rental or Sale");

        javax.swing.GroupLayout jPanelInPropLayout = new javax.swing.GroupLayout(jPanelInProp);
        jPanelInProp.setLayout(jPanelInPropLayout);
        jPanelInPropLayout.setHorizontalGroup(
            jPanelInPropLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelInPropLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelInPropLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextInPropertyAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelInPropLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel8)
                        .addComponent(jCBInPropertyOwner, 0, 220, Short.MAX_VALUE)
                        .addComponent(jLabel9)
                        .addComponent(jCBInPropertyYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextInPropertySize, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel10)
                        .addComponent(jLabel11)
                        .addComponent(jTextInPropertyCity)
                        .addComponent(jLabel12)
                        .addComponent(jLabel13)
                        .addComponent(jCBInPropertyCounty, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextInPropertyZip, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel14)
                    .addComponent(jLabel17)
                    .addComponent(propertyVar1)
                    .addComponent(propertyVar2)
                    .addComponent(propertyVar3)
                    .addGroup(jPanelInPropLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jTextInPropertyVar3, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jTextInPropertyVar2, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jTextInPropertyVar1, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jCBInPropertyType, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelInPropLayout.createSequentialGroup()
                            .addGroup(jPanelInPropLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jCBInPropertyBed, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel16))
                            .addGap(34, 34, 34)
                            .addGroup(jPanelInPropLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel15)
                                .addComponent(jCBInPropertyBath, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jLabel18)
                    .addComponent(propertyVar4)
                    .addComponent(propertyVar5)
                    .addComponent(propertyVar6)
                    .addGroup(jPanelInPropLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jTextInPropertyVar6, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jTextInPropertyVar5, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jTextInPropertyVar4, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jCBInPropertyRS, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(245, Short.MAX_VALUE))
        );
        jPanelInPropLayout.setVerticalGroup(
            jPanelInPropLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelInPropLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addGap(0, 0, 0)
                .addComponent(jTextInPropertyAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(jLabel12)
                .addGap(0, 0, 0)
                .addComponent(jTextInPropertyCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(jLabel13)
                .addGap(0, 0, 0)
                .addComponent(jTextInPropertyZip, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(jLabel9)
                .addGap(0, 0, 0)
                .addComponent(jCBInPropertyOwner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel10)
                .addGap(3, 3, 3)
                .addComponent(jTextInPropertySize, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel11)
                .addGap(2, 2, 2)
                .addComponent(jCBInPropertyYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(jLabel14)
                .addGap(0, 0, 0)
                .addComponent(jCBInPropertyCounty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addGroup(jPanelInPropLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(jLabel16))
                .addGap(0, 0, 0)
                .addGroup(jPanelInPropLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCBInPropertyBed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCBInPropertyBath, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addComponent(jLabel17)
                .addGap(2, 2, 2)
                .addComponent(jCBInPropertyType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(propertyVar1)
                .addGap(0, 0, 0)
                .addComponent(jTextInPropertyVar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(propertyVar2)
                .addGap(0, 0, 0)
                .addComponent(jTextInPropertyVar2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(propertyVar3)
                .addGap(0, 0, 0)
                .addComponent(jTextInPropertyVar3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55)
                .addComponent(jLabel18)
                .addGap(1, 1, 1)
                .addComponent(jCBInPropertyRS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(propertyVar4)
                .addGap(0, 0, 0)
                .addComponent(jTextInPropertyVar4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(propertyVar5)
                .addGap(0, 0, 0)
                .addComponent(jTextInPropertyVar5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(propertyVar6)
                .addGap(0, 0, 0)
                .addComponent(jTextInPropertyVar6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(224, Short.MAX_VALUE))
        );

        jScrollPane2.setViewportView(jPanelInProp);

        javax.swing.GroupLayout jPanelInPropertyLayout = new javax.swing.GroupLayout(jPanelInProperty);
        jPanelInProperty.setLayout(jPanelInPropertyLayout);
        jPanelInPropertyLayout.setHorizontalGroup(
            jPanelInPropertyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelInPropertyLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonPropAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56)
                .addComponent(jButtonProbClear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(238, 238, 238))
            .addGroup(jPanelInPropertyLayout.createSequentialGroup()
                .addComponent(jScrollPane2)
                .addContainerGap())
        );
        jPanelInPropertyLayout.setVerticalGroup(
            jPanelInPropertyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelInPropertyLayout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 458, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelInPropertyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonProbClear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonPropAdd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPaneInput.addTab("Property", jPanelInProperty);

        jButtonTenantAdd.setText("Add");
        jButtonTenantAdd.setMaximumSize(new java.awt.Dimension(70, 29));
        jButtonTenantAdd.setMinimumSize(new java.awt.Dimension(70, 29));
        jButtonTenantAdd.setPreferredSize(null);
        jButtonTenantAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTenantAddActionPerformed(evt);
            }
        });

        jButtonTenantClear.setText("Clear");
        jButtonTenantClear.setMaximumSize(new java.awt.Dimension(70, 29));
        jButtonTenantClear.setMinimumSize(new java.awt.Dimension(70, 29));
        jButtonTenantClear.setPreferredSize(null);

        jCBInTenantProperty.setModel(new javax.swing.DefaultComboBoxModel(propertyCB));

        jCBInTenantDependents.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8+" }));

        jLabel19.setText("Name");

        jLabel20.setText("Email");

        jLabeTlPN.setText("Phone Number");

        jLabel22.setText("Number of Dependents");

        jLabel23.setText("Property");

        javax.swing.GroupLayout jPanelInTenantLayout = new javax.swing.GroupLayout(jPanelInTenant);
        jPanelInTenant.setLayout(jPanelInTenantLayout);
        jPanelInTenantLayout.setHorizontalGroup(
            jPanelInTenantLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelInTenantLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonTenantAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56)
                .addComponent(jButtonTenantClear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(238, 238, 238))
            .addGroup(jPanelInTenantLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelInTenantLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCBInTenantDependents, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelInTenantLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jTextInTenantPhone, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jTextInTenantEmail, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 146, Short.MAX_VALUE))
                    .addComponent(jLabel20)
                    .addComponent(jLabeTlPN)
                    .addComponent(jLabel22)
                    .addGroup(jPanelInTenantLayout.createSequentialGroup()
                        .addGroup(jPanelInTenantLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextInTenantName, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel19))
                        .addGap(146, 146, 146)
                        .addGroup(jPanelInTenantLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel23)
                            .addComponent(jCBInTenantProperty, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelInTenantLayout.setVerticalGroup(
            jPanelInTenantLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelInTenantLayout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(jPanelInTenantLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(jLabel23))
                .addGap(0, 0, 0)
                .addGroup(jPanelInTenantLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextInTenantName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCBInTenantProperty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addComponent(jLabel20)
                .addGap(1, 1, 1)
                .addComponent(jTextInTenantEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jLabeTlPN)
                .addGap(0, 0, 0)
                .addComponent(jTextInTenantPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(jLabel22)
                .addGap(0, 0, 0)
                .addComponent(jCBInTenantDependents, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 233, Short.MAX_VALUE)
                .addGroup(jPanelInTenantLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonTenantClear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonTenantAdd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPaneInput.addTab("Tenant", jPanelInTenant);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPaneInput)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPaneInput)
        );

        jPanelMain.addTab("Insert Data", jPanel1);

        jCBOutTenantName.setModel(new javax.swing.DefaultComboBoxModel(tenantCB));

        jLabel39.setText("Select Tenant");

        jButtonOutTenantLoad.setText("Load");
        jButtonOutTenantLoad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOutTenantLoadActionPerformed(evt);
            }
        });

        jTAOutTenantInfo.setColumns(20);
        jTAOutTenantInfo.setRows(5);
        jScrollPane4.setViewportView(jTAOutTenantInfo);

        jTAOutTenantPay.setColumns(20);
        jTAOutTenantPay.setRows(5);
        jScrollPane5.setViewportView(jTAOutTenantPay);

        javax.swing.GroupLayout jPanelOutTenantLayout = new javax.swing.GroupLayout(jPanelOutTenant);
        jPanelOutTenant.setLayout(jPanelOutTenantLayout);
        jPanelOutTenantLayout.setHorizontalGroup(
            jPanelOutTenantLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelOutTenantLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelOutTenantLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel39)
                    .addGroup(jPanelOutTenantLayout.createSequentialGroup()
                        .addGroup(jPanelOutTenantLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jCBOutTenantName, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(75, 75, 75)
                        .addGroup(jPanelOutTenantLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonOutTenantLoad)
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(82, Short.MAX_VALUE))
        );
        jPanelOutTenantLayout.setVerticalGroup(
            jPanelOutTenantLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelOutTenantLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel39)
                .addGap(0, 0, 0)
                .addGroup(jPanelOutTenantLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCBOutTenantName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonOutTenantLoad))
                .addGap(65, 65, 65)
                .addGroup(jPanelOutTenantLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 355, Short.MAX_VALUE)
                    .addComponent(jScrollPane4))
                .addGap(36, 36, 36))
        );

        jTabbedPane1.addTab("Tenant Info", jPanelOutTenant);

        jCBOutProp.setModel(new javax.swing.DefaultComboBoxModel(propertyCB));

        jButtonOutPropLoad.setText("Load");
        jButtonOutPropLoad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOutPropLoadActionPerformed(evt);
            }
        });

        jLabel34.setText("Select Property");

        jTAOutPropInfo.setColumns(20);
        jTAOutPropInfo.setRows(5);
        jScrollPane3.setViewportView(jTAOutPropInfo);

        jTAOutPropRepair.setColumns(20);
        jTAOutPropRepair.setRows(5);
        jScrollPane6.setViewportView(jTAOutPropRepair);

        javax.swing.GroupLayout jPanelOutPropLayout = new javax.swing.GroupLayout(jPanelOutProp);
        jPanelOutProp.setLayout(jPanelOutPropLayout);
        jPanelOutPropLayout.setHorizontalGroup(
            jPanelOutPropLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelOutPropLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelOutPropLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel34)
                    .addGroup(jPanelOutPropLayout.createSequentialGroup()
                        .addGroup(jPanelOutPropLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 312, Short.MAX_VALUE)
                            .addComponent(jCBOutProp, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(jPanelOutPropLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelOutPropLayout.createSequentialGroup()
                                .addGap(75, 75, 75)
                                .addComponent(jButtonOutPropLoad))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelOutPropLayout.createSequentialGroup()
                                .addGap(41, 41, 41)
                                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        jPanelOutPropLayout.setVerticalGroup(
            jPanelOutPropLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelOutPropLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel34)
                .addGap(0, 0, 0)
                .addGroup(jPanelOutPropLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCBOutProp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonOutPropLoad))
                .addGap(65, 65, 65)
                .addGroup(jPanelOutPropLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 347, Short.MAX_VALUE)
                    .addComponent(jScrollPane3))
                .addContainerGap(55, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Property Info", jPanelOutProp);

        jLabel40.setText("Select Repair Record");

        jCBOutRepair.setModel(new javax.swing.DefaultComboBoxModel(repairCB));

        jButtonOutRepair.setText("Load");

        jTextArea5.setColumns(20);
        jTextArea5.setRows(5);
        jScrollPane7.setViewportView(jTextArea5);

        javax.swing.GroupLayout jPanelOutRepairLayout = new javax.swing.GroupLayout(jPanelOutRepair);
        jPanelOutRepair.setLayout(jPanelOutRepairLayout);
        jPanelOutRepairLayout.setHorizontalGroup(
            jPanelOutRepairLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelOutRepairLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelOutRepairLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 401, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelOutRepairLayout.createSequentialGroup()
                        .addComponent(jCBOutRepair, javax.swing.GroupLayout.PREFERRED_SIZE, 401, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(53, 53, 53)
                        .addComponent(jButtonOutRepair))
                    .addComponent(jLabel40))
                .addContainerGap(141, Short.MAX_VALUE))
        );
        jPanelOutRepairLayout.setVerticalGroup(
            jPanelOutRepairLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelOutRepairLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel40)
                .addGap(0, 0, 0)
                .addGroup(jPanelOutRepairLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCBOutRepair, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonOutRepair))
                .addGap(65, 65, 65)
                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(190, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Repair Info", jPanelOutRepair);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        jPanelMain.addTab("Read Data", jPanel2);

        getContentPane().add(jPanelMain, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonPropAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPropAddActionPerformed
        // TODO add your handling code here:
        String propName = jTextInPropertyAddress.getText();
        String propCity = jTextInPropertyCity.getText();
        String propZip = jTextInPropertyZip.getText();
        String OwnerName = jCBInPropertyOwner.getSelectedItem().toString();
        int size = Integer.parseInt(jTextInPropertySize.getText().toString());
        int year = jCBInPropertyYear.getSelectedIndex() + 1917;
        String county = jCBInPropertyCounty.getSelectedItem().toString();
        int bedNum = jCBInPropertyBed.getSelectedIndex();
        int bathNum = jCBInPropertyBath.getSelectedIndex();
        
    }//GEN-LAST:event_jButtonPropAddActionPerformed

    private void jButtonStoreAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonStoreAddActionPerformed
        // TODO add your handling code here:
        String storeName = jTextInStoreName.getText();
        String storeAddress = jTextInStoreAddress.getText();
        String storePhone = jTextInStorePhone.getText();
        
        jButtonStoreClearActionPerformed(null);
    }//GEN-LAST:event_jButtonStoreAddActionPerformed

    private void jButtonPayAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPayAddActionPerformed
        // TODO add your handling code here:
        String propName = jCBInPayProperty.getSelectedItem().toString();
        String tenantName = jCBInPayTenant.getSelectedItem().toString();
        int tenantPay = Integer.parseInt(jTextInPayTenant.getText());
        int ownerPay = Integer.parseInt(jTextInPayOwner.getText());
        int tMonth = jCBInPayTM.getSelectedIndex()+1;
        int oMonth = jCBInPayOM.getSelectedIndex()+1;
        int tYear =  jCBInPayTY.getSelectedIndex()+2010;
        int oYear =  jCBInPayOY.getSelectedIndex()+2010;
        jButtonPayClearActionPerformed(null);
    }//GEN-LAST:event_jButtonPayAddActionPerformed

    private void jButtonTenantAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTenantAddActionPerformed
        // TODO add your handling code here:
        String tenantName = jTextInTenantName.getText();
        String tenantEmail = jTextInTenantEmail.getText();
        String tenantPhone = jTextInTenantPhone.getText();
        int tenantDep = jCBInTenantDependents.getSelectedIndex();
        String PropertyID = jCBInTenantProperty.getSelectedItem().toString();
        
    }//GEN-LAST:event_jButtonTenantAddActionPerformed

    private void jButtonOGAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOGAddActionPerformed
        // TODO add your handling code here:
        String ownerAdd = jCBInOGOwner.getSelectedItem().toString();
        String ownerGroup = jCBInOGGroup.getSelectedItem().toString();
        String findOwnerID = "Select ownerID from owner where name = \"" +ownerAdd+"\"";
        String findGroupID = "Select ownerID from owner where name = \"" +ownerGroup+"\"";
        System.out.println(findOwnerID + "\n" + findGroupID);
    }//GEN-LAST:event_jButtonOGAddActionPerformed

    private void jButtonOwnerAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOwnerAddActionPerformed
        // TODO add your handling code here:
        String ownerName = jTextInOwnerName.getText();
        String ownerPhone = jTextInOwnerPhoneNum.getText();
        String ownerEmail = jTextInOwnerEmail.getText();
        
        jButtonOwnerClearActionPerformed(null); 
    }//GEN-LAST:event_jButtonOwnerAddActionPerformed

    private void jCBInPropertyRSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCBInPropertyRSActionPerformed
        // TODO add your handling code here:
        int type =  jCBInPropertyRS.getSelectedIndex();
        jTextInPropertyVar4.setText("");
        jTextInPropertyVar5.setText("");
        jTextInPropertyVar6.setText("");
        if (type == 0){ //rental
            propertyVar4.setText("Price");
            propertyVar5.setText("Max Tenants");
            propertyVar6.setText("Fee in %");
        }
        else if (type == 1){ //sale
            propertyVar4.setText("Sale Date");
            propertyVar5.setText("Sale Price");
            propertyVar6.setText("Fee in %");
        }
    }//GEN-LAST:event_jCBInPropertyRSActionPerformed

    private void jButtonRCAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRCAddActionPerformed
        // TODO add your handling code here:
        String rCName = jTextInRCName.getText();
        String rCPhone = jTextInRCPhone.getText();
    }//GEN-LAST:event_jButtonRCAddActionPerformed

    private void jCBInPropertyTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCBInPropertyTypeActionPerformed
        // TODO add your handling code here:
        int type =  jCBInPropertyType.getSelectedIndex();
       jTextInPropertyVar1.setText("");
       jTextInPropertyVar2.setText("");
       jTextInPropertyVar3.setText("");
       if (type == 0){ //condo
        propertyVar1.setText("Condo Number");
        propertyVar2.setText("NA");
        propertyVar3.setText("NA");
       }
       else if (type == 1){ //townhouse
        propertyVar1.setText("End Unit? (enter yes/no)");
        propertyVar2.setText("Number of Floors");
        propertyVar3.setText("Garage Size");
       }
       else if (type == 2){ //SFH
        propertyVar1.setText("Garage size");
        propertyVar2.setText("Number of Floors");
        propertyVar3.setText("NA");
       }
    }//GEN-LAST:event_jCBInPropertyTypeActionPerformed

    private void jButtonOutTenantLoadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOutTenantLoadActionPerformed
        // TODO add your handling code here:
        String tenantName = jCBOutTenantName.getSelectedItem().toString();
        String tenantInfo = "Info";
        jTAOutTenantInfo.setText(tenantInfo);
        String getTenantID = "Select tenantID from tenant where name = \"" +tenantName+"\"";
        jTAOutTenantPay.setText(getTenantID);
    }//GEN-LAST:event_jButtonOutTenantLoadActionPerformed

    private void jButtonOutPropLoadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOutPropLoadActionPerformed
        // TODO add your handling code here:
        String propName = jCBOutProp.getSelectedItem().toString();
        String propInfo = "Info";
        jTAOutPropInfo.setText(propInfo);
        String getRepairs = "Select repairID from repair where property = \"" +propName+"\"";
        jTAOutPropRepair.setText(getRepairs);
    }//GEN-LAST:event_jButtonOutPropLoadActionPerformed

    private void jButtonRepairAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRepairAddActionPerformed
        // TODO add your handling code here:
        String propName = jCBInRepairProperty.getSelectedItem().toString();
        int month = Integer.parseInt(jTextInRepairDateM.getText());
        int day = Integer.parseInt(jTextInRepairDateD.getText());
        int year = Integer.parseInt(jTextInRepairDateY.getText());
        String repairCompany = jCBInRepairRC.getSelectedItem().toString();
        String repairmanName = jTextInRepairman.getText();
        String store = jCBInRepairStore.getSelectedItem().toString();
        int rCost = Integer.parseInt(jTextInRepairRCost.getText());
        int mCost = Integer.parseInt(jTextInRepairMCost.getText());
        
        jButtonRepairClearActionPerformed(null);
    }//GEN-LAST:event_jButtonRepairAddActionPerformed

    private void jButtonOwnerClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOwnerClearActionPerformed
        // TODO add your handling code here:
        jTextInOwnerName.setText(null);
        jTextInOwnerPhoneNum.setText(null);
        jTextInOwnerEmail.setText(null);
    }//GEN-LAST:event_jButtonOwnerClearActionPerformed

    private void jButtonPayClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPayClearActionPerformed
        // TODO add your handling code here:
        jTextInPayTenant.setText(null);
        jTextInPayOwner.setText(null);
    }//GEN-LAST:event_jButtonPayClearActionPerformed

    private void jButtonRepairClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRepairClearActionPerformed
        // TODO add your handling code here:
        jTextInRepairDateM.setText(null);
        jTextInRepairDateD.setText(null);
        jTextInRepairDateY.setText(null);
        jTextInRepairman.setText(null);
        jTextInRepairRCost.setText(null);
        jTextInRepairMCost.setText(null);
    }//GEN-LAST:event_jButtonRepairClearActionPerformed

    private void jButtonStoreClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonStoreClearActionPerformed
        // TODO add your handling code here:
        jTextInStoreName.setText(null);
        jTextInStoreAddress.setText(null);
        jTextInStorePhone.setText(null);
    }//GEN-LAST:event_jButtonStoreClearActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mainPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mainPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mainPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mainPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
                new mainPanel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonClear;
    private javax.swing.JButton jButtonOGAdd;
    private javax.swing.JButton jButtonOutPropLoad;
    private javax.swing.JButton jButtonOutRepair;
    private javax.swing.JButton jButtonOutTenantLoad;
    private javax.swing.JButton jButtonOwnerAdd;
    private javax.swing.JButton jButtonOwnerClear;
    private javax.swing.JButton jButtonPayAdd;
    private javax.swing.JButton jButtonPayClear;
    private javax.swing.JButton jButtonProbClear;
    private javax.swing.JButton jButtonPropAdd;
    private javax.swing.JButton jButtonRCAdd;
    private javax.swing.JButton jButtonRCClear;
    private javax.swing.JButton jButtonRepairAdd;
    private javax.swing.JButton jButtonRepairClear;
    private javax.swing.JButton jButtonStoreAdd;
    private javax.swing.JButton jButtonStoreClear;
    private javax.swing.JButton jButtonTenantAdd;
    private javax.swing.JButton jButtonTenantClear;
    private javax.swing.JComboBox<String> jCBInOGGroup;
    private javax.swing.JComboBox<String> jCBInOGOwner;
    private javax.swing.JComboBox<String> jCBInPayOM;
    private javax.swing.JComboBox<String> jCBInPayOY;
    private javax.swing.JComboBox<String> jCBInPayProperty;
    private javax.swing.JComboBox<String> jCBInPayTM;
    private javax.swing.JComboBox<String> jCBInPayTY;
    private javax.swing.JComboBox<String> jCBInPayTenant;
    private javax.swing.JComboBox<String> jCBInPropertyBath;
    private javax.swing.JComboBox<String> jCBInPropertyBed;
    private javax.swing.JComboBox<String> jCBInPropertyCounty;
    private javax.swing.JComboBox<String> jCBInPropertyOwner;
    private javax.swing.JComboBox<String> jCBInPropertyRS;
    private javax.swing.JComboBox<String> jCBInPropertyType;
    private javax.swing.JComboBox<String> jCBInPropertyYear;
    private javax.swing.JComboBox<String> jCBInRepairProperty;
    private javax.swing.JComboBox<String> jCBInRepairRC;
    private javax.swing.JComboBox<String> jCBInRepairStore;
    private javax.swing.JComboBox<String> jCBInTenantDependents;
    private javax.swing.JComboBox<String> jCBInTenantProperty;
    private javax.swing.JComboBox<String> jCBOutProp;
    private javax.swing.JComboBox<String> jCBOutRepair;
    private javax.swing.JComboBox<String> jCBOutTenantName;
    private javax.swing.JLabel jLabeTlPN;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelRC;
    private javax.swing.JTabbedPane jPaneInput;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanelInOwner;
    private javax.swing.JPanel jPanelInOwnerGroup;
    private javax.swing.JPanel jPanelInPayment;
    private javax.swing.JPanel jPanelInProp;
    private javax.swing.JPanel jPanelInProperty;
    private javax.swing.JPanel jPanelInRepair;
    private javax.swing.JPanel jPanelInRepairCompany;
    private javax.swing.JPanel jPanelInStores;
    private javax.swing.JPanel jPanelInTenant;
    private javax.swing.JTabbedPane jPanelMain;
    private javax.swing.JPanel jPanelOutProp;
    private javax.swing.JPanel jPanelOutRepair;
    private javax.swing.JPanel jPanelOutTenant;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JTextArea jTAOutPropInfo;
    private javax.swing.JTextArea jTAOutPropRepair;
    private javax.swing.JTextArea jTAOutTenantInfo;
    private javax.swing.JTextArea jTAOutTenantPay;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextArea jTextArea5;
    private javax.swing.JTextField jTextInOwnerEmail;
    private javax.swing.JTextField jTextInOwnerName;
    private javax.swing.JTextField jTextInOwnerPhoneNum;
    private javax.swing.JTextField jTextInPayOwner;
    private javax.swing.JTextField jTextInPayTenant;
    private javax.swing.JTextField jTextInPropertyAddress;
    private javax.swing.JTextField jTextInPropertyCity;
    private javax.swing.JTextField jTextInPropertySize;
    private javax.swing.JTextField jTextInPropertyVar1;
    private javax.swing.JTextField jTextInPropertyVar2;
    private javax.swing.JTextField jTextInPropertyVar3;
    private javax.swing.JTextField jTextInPropertyVar4;
    private javax.swing.JTextField jTextInPropertyVar5;
    private javax.swing.JTextField jTextInPropertyVar6;
    private javax.swing.JTextField jTextInPropertyZip;
    private javax.swing.JTextField jTextInRCName;
    private javax.swing.JTextField jTextInRCPhone;
    private javax.swing.JTextField jTextInRepairDateD;
    private javax.swing.JTextField jTextInRepairDateM;
    private javax.swing.JTextField jTextInRepairDateY;
    private javax.swing.JTextField jTextInRepairMCost;
    private javax.swing.JTextField jTextInRepairRCost;
    private javax.swing.JTextField jTextInRepairman;
    private javax.swing.JTextField jTextInStoreAddress;
    private javax.swing.JTextField jTextInStoreName;
    private javax.swing.JTextField jTextInStorePhone;
    private javax.swing.JTextField jTextInTenantEmail;
    private javax.swing.JTextField jTextInTenantName;
    private javax.swing.JTextField jTextInTenantPhone;
    private javax.swing.JLabel propertyVar1;
    private javax.swing.JLabel propertyVar2;
    private javax.swing.JLabel propertyVar3;
    private javax.swing.JLabel propertyVar4;
    private javax.swing.JLabel propertyVar5;
    private javax.swing.JLabel propertyVar6;
    // End of variables declaration//GEN-END:variables
    private String[] tenantCB;
    private String[] propertyCB;
    private String[] ownerCB;
    private String[] repairCB;
    private String[] repairCompanyCB;
    private String[] storeCB;
    private String[] countyCB;
}
